//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAEscaneosRDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lpns
    {
        public int Id { get; set; }
        public string CodigoLpn { get; set; }
        public Nullable<System.DateTime> FechaEscaneo { get; set; }
        public int Tags_Id { get; set; }
        public int Usuarios_Id { get; set; }
    
        public virtual Tags Tags { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
