//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAEscaneosRDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tags()
        {
            this.Lpns = new HashSet<Lpns>();
        }
    
        public int Id { get; set; }
        public string TagNumber { get; set; }
        public string Trailer { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int TagStates_Id { get; set; }
        public int Trailers_Id { get; set; }
    
        public virtual TagStates TagStates { get; set; }
        public virtual Trailers Trailers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lpns> Lpns { get; set; }
    }
}
